### ISSUE TITLE
Example function code for get_func_dict

### ISSUE THREAD

**Issue by annchenknodt** [ForrestCKoch/DCDF#1]
Hi, I'm working on calculating DDF in my data per your 2021 NI paper.  Doing this with the provided code seems straightforward enough, but I'm not quite sure how to specify the function that gets input to get_func_dict.  Would you be able to provide an example text file based on what you used for the paper?  Thanks!

**Comment by ForrestCKoch** [comment]
My bad! I'm not sure why I hadn't already included this.  I've added an example text file in https://github.com/ForrestCKoch/DCDF/commit/21d32782e949f82badab261e030b579f8858c9e6 (see dcdf/sample_equations.txt).  I've included 3 equations here:
```
sum_difference: np.sum(r-s)*b
sum: np.sum(s)*b
exp_difference_1e1: np.sum(np.exp(10*(r-s)))*b
```
So the general structure is 
```
{formula name}:{equation}
```
where 'equation' is basically just python code that gets executed (note that you can use numpy functions too). The variables `r`, `s`, and `b` represent the reference frequency, subject frequency, and bin-width respectively.  In hindsight I should have used Gaussian-quadrature to do the numerical integration, but what's done is done ...

It sounds like you're actually digging around the Python code, so I might mention that there is a commandline interface available.  The code is dcdf/cli.py, but the package will create an executable called dcdf if you have installed the package.  Again, I probably should've provided more information about how to use the CLI, however, the help menu is pretty comprehensive (use the '-h' flag).  An example of running it this way looks something like
```
dcdf -b reference_paths.txt -e subject_paths.txt -p -c 8 -q sample_equations.txt -L -0.01 -U 0.01 -B 10000 -Q -M 0.05 -S 0.95 -f > results.csv
```

**Comment by annchenknodt** [comment]
Great, thanks for the quick response!  The sample equations and command line run example are very helpful!
